version: "3"

services:
  backend:
    build: backend
    image: backend
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778
    ports:
      - "0.0.0.0:8082:8080"

  gateway:
    build: gateway
    image: gateway
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778
    ports:
      - "0.0.0.0:8081:8080"

  client:
    build: client
    image: client
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778
    ports:
      - "0.0.0.0:8080:8080"

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "0.0.0.0:5775:5775/udp"
      - "0.0.0.0:6831:6831/udp"
      - "0.0.0.0:6832:6832/udp"
      - "0.0.0.0:5778:5778"
      - "0.0.0.0:14268:14268"
      - "0.0.0.0:9411:9411"
      - "0.0.0.0:16686:16686"

networks:
  default:
